creaete target dir

diff --git a/.github/workflows/build-isf.yml b/.github/workflows/build-isf.yml
--- a/.github/workflows/build-isf.yml
+++ b/.github/workflows/build-isf.yml
@@ -93,6 +93,7 @@ jobs:
         else
           echo "No previous Anaconda installation found. Continuing..."
         fi
+        mkdir $CONDA_TARGET_DIR || { echo "Failed to create directory $INSTALL_DIR"; exit 1; }
         pushd .
         cd installer/py${{ inputs.py_version }}
         set -o pipefail
